// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package avionca

type Flight struct {
	FlightNumber string  `json:"flightNumber"`
	Origin       string  `json:"origin"`
	Destination  string  `json:"destination"`
	Departure    string  `json:"departure"`
	Duration     int     `json:"duration"`
	Price        float64 `json:"price"`
}

type Query struct {
}
